# Generated by Django 3.0.7 on 2022-02-01 13:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20220117_1947'),
    ]

    operations = [
        migrations.AlterField(
            model_name='CustomUser',
            name='username',
            field=models.CharField(max_length=25, unique=True, validators=[django.core.validators.RegexValidator(message='Username must consist only of alphanumeric characters and underscores.', regex='^[0-9a-zA-Z_]*$')]),
        ),
    ]
