# Generated by Django 3.0.7 on 2022-02-01 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20220201_1309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='CustomUser',
            name='avatar',
            field=models.ImageField(),
        ),
    ]
