name: Django CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [ 3.8 ]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run Docker
        continue-on-error: true
        run: |
          docker-compose up --build -d
          docker-compose exec -T db psql -U postgres -c "CREATE DATABASE webpoker"
          docker-compose exec -T web python manage.py migrate
      - name: Run Unit Tests
        continue-on-error: true
        run: |
          docker-compose exec -T web coverage run manage.py test tests.tests_unit -v 2 --noinput
          docker-compose exec -T web coverage report
      - name: Run Integration Tests
        continue-on-error: true
        run: |
          docker-compose exec -T web python manage.py test tests.tests_integration -v 2 --noinput
          docker-compose exec -T db psql -U postgres -c "DROP DATABASE test_webpoker"
      - name: Run System Tests
        continue-on-error: true
        run: |
          docker-compose exec -T web python manage.py test tests.tests_sys -v 2 --noinput
      - name: Kill Docker
        run: |
          docker-compose down
