name: Django CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.8]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install braintree mysqlclient apprise
    - name: Run Docker
      run: |
        docker-compose up --build -d
        docker-compose exec db psql -U postgres -c "CREATE DATABASE webpoker"
        docker-compose exec web python manage.py migrate
    - name: Run Unit Tests
      run: |
        cd project
        docker-compose exec web python manage.py test
    - name: Kill Docker
      run: |
        docker-compose down
